name: 07-expressions
run-name: 07-expressions | DEBUG - ${{ inputs.debug && 'ON' || 'OFF' }}
on:
  push:
  workflow_dispatch:
    inputs:
      debug:
        description: "Enable debug mode"
        type: boolean
        default: false
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
    - name: debug print start-up data
      if: ${{ inputs.debug }}
      run: |
        echo "Triggered By: github.event_name"
        echo "Branch: ${{ github.ref }}"
        echo "Commit SHA: ${{ github.sha }}"
        echo "Runner OS: ${{ runner.os }}"
    - name: Print when triggered from main
      if: ${{ inputs.debug }} && github.ref == 'refs/heads/main'
      run: echo "Triggered from main"
    - name: Greeting
      run: echo "Finished"